### ISSUE TITLE
다운로드 안됨.

### ISSUE THREAD

**Issue by Dobob1022** [Team-IVIag/IVIag-Viewer#10]
마루마루 막혔나보네요 
yuncomics.com이후 클라우드 프록시 가면 거기서 부터 막히네요 

혹시 몰라서 로그 첨부해둡니다.

========LOG========
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/arch
ves/1685343
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1685343'...
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/arch
ves/1695586
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1695586'...
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/arch
ves/1705230
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1705230'...
IVIagParser Try detour CloudProxy...
IVIagParser Try detour CloudProxy...
IVIagParser Try detour CloudProxy...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=4965d577cae4f01031f45dc6
4efcf4e;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1705230'...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=4965d577cae4f01031f45dc6
4efcf4e;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1695586'...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=4965d577cae4f01031f45dc6
4efcf4e;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1685343'...
MaruMangaParser Fail detour CloudProxy.
[2016-07-03 07:52:41][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fai
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

MaruMangaParser Fail detour CloudProxy.
[2016-07-03 07:52:41][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fai
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

MaruMangaParser Fail detour CloudProxy.
[2016-07-03 07:52:42][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fai
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/arch
ves/1705230
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1705230'...
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/arch
ves/1695586
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/arch
ves/1685343
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1685343'...
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1695586'...
IVIagParser Try detour CloudProxy...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=1f0bd52477996c8f35276b41
691ce93;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1695586'...
MaruMangaParser Fail detour CloudProxy.

**Comment by HelloWorld017** [comment]
blog.yuncomics.com 으로 바뀌면서 생긴 문제 같네요

**Comment by Dobob1022** [comment]
어떤거 수정하면 해결이 될까요?

**Comment by HelloWorld017** [comment]
일단 코드는 수정했고, 빌드만 하면 됩니다. 제가 현재 학생신분이라 빌드해서 릴리즈하려면 주말은 돼야할듯 하네요.

**Comment by HelloWorld017** [comment]
#11
